spring:
  datasource:
    url: jdbc:h2:./school #En vez de una BD en la nube, lo guardamos en un fichero
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update #Con update se crean las tablas si no existen y compara las entidades con las tablas. Si falta algún campo, lo añade.
    open-in-view: false
    show-sql: true #Para ver las consultas SQL que se ejecutan en consola
    properties:
      hibernate:
        format_sql: true #Para que las consultas SQL se vean bien formateadas y legibles
  main:
    allow-circular-references: true #Para que no de error al tener referencias circulares en las entidades
  h2:
    console:
      enabled: true #Para que se pueda acceder a la consola de H2 (antes era active: true)
      path: /console #Ruta para acceder a la consola de H2
server:
  servlet:
    context-path: /school #Para que las rutas (endpoints) empiecen por /school